### ISSUE TITLE
Error when running pysb.simulator.StochKitSimulator

### ISSUE THREAD

**Issue by dehlerni** [StochSS/StochKit#21]
When running the pysb.simulator.StochKitSimulator function with my pysb model, I receive the error message:
    f.write(stoch_xml)

TypeError: write() argument must be str, not bytes

This is in the trajectories portion of stochkit.py.
I appreciate any help you can provide.

**Comment by alubbock** [comment]
Hi @dehlerni , PySB developer here. I've only just seen this, but this looks like it might be an old issue with the PySB StochKit interface rather than StochKit itself. If there's still a problem, please open an issue over at [PySB](https://github.com/pysb/pysb). Thanks!
