### ISSUE TITLE
File "Installation_instructions.pdf" missing

### ISSUE THREAD

**Issue by fjplopes** [StochSS/StochKit#25]
Dear,
I just download StochKit2 from sourceforge.net but the Installation_instructions.pdf is missing. 
Could you please help me to install StochKit2 on a Windows machine?
Thanks,
Francisco

**Comment by briandrawert** [comment]
Unfortunately, supporting StochKit on Windows is very challenging and we have no developers to work on it at this time.  StochKit is being sunset and we are strongly recommending that every switch to GillesPy2, our new and simulation platform which is under active development and has a great deal of improvements.  [https://github.com/StochSS/GillesPy2](https://github.com/StochSS/GillesPy2)
